version: '3'

services:
  nestjs:
    build: 
      context: .
      dockerfile: DockerFile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: testDB
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: